### ISSUE TITLE
Add last updated time to VSB data

### ISSUE THREAD

**Issue by jinh0** [jinh0/cloudberry.fyi#63]

**Comment by andrzeng** [comment]
do you mean the last time the course info was fetched?

**Comment by jinh0** [comment]
> do you mean the last time the course info was fetched?

Yeah, so right now every time a user goes on a course page, we send a request to VSB. But that obviously is slow and actually concerning (since VSB can literally be shut down in matter of seconds if there's too many requests).

So I thought we would record the last retrieved time in the VSB data, if a new user's request is, say within five minutes (maybe 3), then we shouldn't ask VSB, it should get it from our cache. Then all the traffic going to popular courses like COMP 250 won't break VSB and it would be faster to fetch.

But this means we need to store VSB data in an actual database, and not a JSON file like right now... and that's its own headache.
